---
title: "Overview"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# What this Package Does

The `DSbulkUploadR` package only requires that you use a very few functions including `bulk_reference_generation()`. This function takes an input .txt file generated by `make_input_template()` and uses it to:

1) Create draft reference(s) on DataStore
2) Populate each draft reference with the supplied information from the input.txt file
3) Upload *all* the file(s) in the specified director(ies) to the draft reference(s)

The `bulk_reference generation()` function will return a dataframe containing all of the information supplied in the input.txt file with one additional column containing the datastore reference ID for each newly created reference. You may wish to write this dataframe to a .csv, .txt, or similar for your records.

# What this Package Doesn't
1) Connect to the VPN or to the NPS network for you (you must be connected to the network to use these functions)
2) Modify the input template to include your data
3) Register ORCiDs for authors
4) Add an author's ORCID to their Active Directory/Entra ID account
5) Provide a peer, technical, administrative, or other review of the reference(s) created
6) Add taxonomy to the reference(s)
7) Activate ("publish") the reference(s)

# Supported DataStore Reference Types
Audio Recording

# Supported File Types
Upload of all file types is supported. There is no distinction made among file types and no need to designate specific file types. Changing the default settings can result in virtually limitless numbers and sizes of files to upload. Use caution when changing the default settings!

# Upcoming changes and additions:
1) Support for adding references to projects on DataStore
2) Support for additional reference types
3) Any other ideas or suggestions? Feel free to [submit them as an Issue](https://github.com/nationalparkservice/DSbulkUploadR/issues) on github!
